# Generated by Django 4.2.1 on 2023-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Terrible'), (2, '2 - Bad'), (3, '3 - Okay'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
