# Generated by Django 4.2.1 on 2023-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(default=1000000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(default=1000000, primary_key=True, serialize=False)),
            ],
        ),
    ]
